name: OpenWrt-AMD64

on:
  schedule:
    - cron: "0 0 * * 5"

  workflow_dispatch:

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cleanup
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/share/rust
          sudo rm -rf /usr/lib/google-cloud-sdk
          sudo rm -rf /usr/include/php
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/share/rust
          sudo rm -rf /usr/local/share/vcpkg
          sudo rm -rf /usr/lib/firefoxr
          echo -e "\033[32;1m==> Free space: \033[0m" && df -h

      - name: Environment
        run: ./openwrt_env.sh

      - name: Update
        run: ./openwrt_update.sh

      - name: Build
        run: ./openwrt_build.sh amd64_generic_defconfig

      - name: Deliver
        run: |
          echo -e "\033[32;1m==> Free space: \033[0m" && df -h
          cd $GITHUB_WORKSPACE/openwrt/bin/targets/x86/64
          mkdir release && cp *-combined-efi.* release
          cd release && md5sum *.* > md5sums

      - name: Upload
        uses: Difegue/action-megacmd@master
        with:
          args: put $GITHUB_WORKSPACE/openwrt/bin/targets/x86/64/release /OpenWrt/AMD64/$(date +%Y%m%d)
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}
