name: OpenWrt-Amlogic

on:
  schedule:
    - cron: "0 0 * * 5"

  workflow_dispatch:

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cleanup
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          echo -e "\033[32;1m==> Free space: \033[0m" && df -h

      - name: Environment
        run: ./openwrt_env.sh

      - name: Update
        run: ./openwrt_update.sh

      - name: Build X96Air
        run: ./openwrt_build.sh amedia_x96air_defconfig

      - name: Deliver X96Air
        run: |
          echo -e "\033[32;1m==> Free space: \033[0m" && df -h
          cd $GITHUB_WORKSPACE/openwrt/bin/targets/amlogic/sm1
          mkdir amedia_x96air && cp *-x96air-squashfs-* *.buildinfo sha256sums amedia_x96air

      - name: Upload X96Air
        uses: Difegue/action-megacmd@master
        with:
          args: put $GITHUB_WORKSPACE/openwrt/bin/targets/amlogic/sm1/amedia_x96air /OpenWrt/Amlogic/amedia_x96air/$(date +%Y%m%d)
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}
