name: OpenWrt-Amlogic

on:
  schedule:
  - cron: "0 0 * * 5"

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Cleanup
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          echo -e "\033[32;1m==> Free space: \033[0m"
          df -h

      - name: Environment
        run: ./openwrt_env.sh

      - name: Update
        run: ./openwrt_update.sh

      - name: Build-X96Air
        run: ./openwrt_build.sh x96-air_defconfig
